version: '3.4'

services:
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: WordBook/Dockerfile
    ports:
      - "5000:80" 

  testService:
    image: testservice
    build:
      context: .
      dockerfile: testService/Dockerfile
    ports:
      - "5001:80" 

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    #volumes:
    #  - db_volume:/var/lib/postgresql/data
    #  - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      PGPORT: 5432
      POSTGRES_USER: "authuser"
      POSTGRES_PASSWORD: "auth"
      POSTGRES_DB: "auth"