version: '3.4'

services:
  reverseproxy:
    image: reverseproxy
    container_name: reverseproxy
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 8000:80
      - 443:443
    restart: always

  authservice:
    depends_on:
      - reverseproxy
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: authservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #ports:
    #  - "5000:80"
    #  - "7000:443" 

  pcHealth:
    image: testservice
    build:
      context: .
      dockerfile: pcHealth/Dockerfile
    ports:
      - "5001:80" 

  mailService:
    image: mailservice
    build:
      context: .
      dockerfile: mailService/Dockerfile
    ports:
      - "5002:80" 

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

  #mssql:
  #  image: "mcr.microsoft.com/mssql/server:2022-latest"
  #  ports:
  #    - "1433:1433"
  #  container_name: mssql
  #  environment:
  #    - ACCEPT_EULA=y
  #    - SA_PASSWORD=A&VeryComplex123Password
